apiVersion: v1
kind: Service
metadata:
  name: deepstream-rtsp
spec:
  type: NodePort
  selector:
    app: deepstream-sample-app
  ports:
  - name: rtsp
    targetPort: 8554
    port: 8554
    nodePort: 30554
