apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: dev-
resources:
- ../../base
patches:
- patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/command
      value: ["sleep"]
    - op: replace
      path: /spec/template/spec/containers/0/args
      value: ["1000000"]
  target:
    kind: Deployment
    name: deepstream-sample-app
